const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const STORE='l2m_state_v5';let state=JSON.parse(localStorage.getItem(STORE)||'{"items":{},"lists":{}}'),current='AEP',selected=null;
const nets={AEP:'Eau potable',EUS:'Eaux usées',EPL:'Eaux pluviales',UNI:'Unitaire',MLT:'Multiréseaux',ECL:'Éclairage public',BTA:'Basse tension A',HTA:'Haute tension A',HTB:'Haute tension B',TEL:'Télécom',CFA:'Courants faibles',GAZ:'Gaz',CHI:'Chimique',CHU:'Chauffage urbain',HYD:'Hydrocarbures',ARO:'Arrosage',SGN:'Signalisation',NDE:'Non déterminé',FRV:'Fourreau vide'};
const nb={AEP:23,EUS:17,EPL:17,UNI:17,MLT:15,ECL:23,BTA:23,HTA:23,HTB:22,TEL:21,CFA:21,GAZ:15,CHI:15,CHU:15,HYD:15,ARO:15,SGN:19,NDE:15,FRV:15};
const tpl=[['CANALISATION','Canalisation','Linéaires','troncon'],['BRANCHEMENT','Branchement','Linéaires','troncon'],['FOURREAU','Fourreau','Linéaires','troncon'],['REGARD_CIRCULAIRE','Regard circulaire','Ouvrages','ouvrage'],['REGARD_RECTANGULAIRE','Regard rectangulaire','Ouvrages','ouvrage'],['CHAMBRE_TIRAGE','Chambre tirage','Ouvrages','ouvrage'],['ARMOIRE','Armoire','Ouvrages','ouvrage'],['POSTE','Poste','Ouvrages','ouvrage'],['PUITS','Puits','Ouvrages','ouvrage'],['AVALOIR','Avaloir','Ouvrages','ouvrage'],['DEVERSOIR','Déversoir','Ouvrages','ouvrage'],['VANNE','Vanne','Équipements','equipement'],['PURGE','Purge','Équipements','equipement'],['VENTOUSE','Ventouse','Équipements','equipement'],['CLAPET','Clapet','Équipements','equipement'],['COFFRET','Coffret','Équipements','equipement'],['LUMINAIRE','Luminaire','Équipements','equipement'],['BORNE','Borne','Équipements','equipement'],['POTEAU','Poteau','Supports','support'],['APPUI','Appui','Supports','support'],['PLAQUE_CARREE','Plaque carrée','Affleurants','affleurant'],['PLAQUE_RONDE','Plaque ronde','Affleurants','affleurant'],['GRILLE_AVALOIR','Grille avaloir','Affleurants','affleurant']];
const reg={LST_RESEAU:Object.keys(nets),LST_CLASSE_PRECISION:['A','B','C'],LST_MODE_LEVE:['GNSS','Station totale','Détection','Digitalisation'],LST_ETAT_RESEAU:['En service','Abandonné','Projeté','Inconnu'],LST_OUI_NON:['Oui','Non','Inconnu'],LST_FORME:['Circulaire','Rectangulaire','Carrée','Ovoïde','Inconnue'],LST_MATERIAU:['Fonte','PVC','PEHD','Béton','Acier','Inconnu'],LST_VAN_TYPE:['Sectionnement','Branchement','Purge','Ventouse','Inconnue'],LST_LUM_TYPE:['Simple','Double','Projecteur','Borne lumineuse','Inconnu']};
const objects=[];for(const n of Object.keys(nets)){for(let i=0;i<nb[n];i++){let t=tpl[i%tpl.length],code=n+'_'+t[0],type=t[0].toLowerCase();objects.push({uid:code,reseau:n,code,libelle:t[1],groupe_palette:t[2],famille_mcd:t[3],type_mcd:type,selection_attendue:n.toLowerCase()+'_'+type+'_sel',statut_selection:'SEL MANQUANT',statut_icone:'ICONE A VERIFIER',statut_dwg:t[2]==='Linéaires'?'DWG NA':'DWG A VERIFIER',bloc_dwg:t[2]==='Linéaires'?'':t[0]+'.dwg',calque:'ECA_RSX_'+n+'_*',attrs:attrs(n,t[3],type)});}}
function attrs(n,f,t){let p=f.slice(0,3);let a=[A('id','UUID','Identifiant unique','','','Non'),A('res','Liste','Réseau','LST_RESEAU',n.toLowerCase(),'Non'),A(p+'_type','Texte','Type objet','',t,'Non'),A('mlev','Liste','Mode de levé','LST_MODE_LEVE','','Oui'),A('clas','Liste','Classe précision','LST_CLASSE_PRECISION','','Oui'),A('etat','Liste','État réseau','LST_ETAT_RESEAU','','Oui'),A('obs','Texte long','Observation terrain','','','Oui')];if(f==='ouvrage')a.push(A('ouv_forme','Liste','Forme','LST_FORME','','Oui'),A('ouv_prof','Nombre','Profondeur','','','Oui'),A('ouv_mat','Liste','Matériau','LST_MATERIAU','','Oui'));if(t==='vanne')a.push(A('van_type','Liste','Type vanne','LST_VAN_TYPE','','Oui'));if(t==='luminaire')a.push(A('lum_type','Liste','Type luminaire','LST_LUM_TYPE','','Oui'));return a}
function A(champ,type,lib,liste,val,vis){return{champ,type_donnee:type,libelle_attribut:lib,liste_reference:liste,valeur_forcee:val,visible:vis,editable:vis,obligatoire:champ==='obs'?'Non':'Oui'}}
function save(){localStorage.setItem(STORE,JSON.stringify(state))}function st(o){return state.items[o.uid]||{}}function merged(o){return{...o,...st(o),attrs:st(o).attrs||o.attrs}}function dec(o){return merged(o).decision||'À valider'}function cls(v){v=String(v||'').toLowerCase();return v.includes('valid')||v.includes('ok')?'ok':v.includes('corriger')||v.includes('verifier')?'warn':v.includes('manquant')||v.includes('exclu')?'bad':''}function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function init(){let groups=[...new Set(objects.map(o=>o.groupe_palette))];$('#groupFilter').innerHTML='<option value="">Tous groupes</option>'+groups.map(g=>'<option>'+g+'</option>').join('');['search','decisionFilter','groupFilter'].forEach(id=>$('#'+id).addEventListener(id==='search'?'input':'change',main));$('#exportBtn').onclick=exportJson;$('#syncBtn').onclick=()=>alert('Exporter JSON puis committer le fichier de validation dans Git.');$$('#editDialog .tabs button').forEach(b=>b.onclick=()=>tab(b.dataset.tab));render()}
function set(uid,p){state.items[uid]={...(state.items[uid]||{}),...p};save();render()}function render(){stats();nav();main()}function stats(){let ok=0,co=0,to=0;objects.forEach(o=>dec(o)==='Validé'?ok++:dec(o)==='À corriger'?co++:dec(o)==='Exclu'?0:to++);$('#stats').innerHTML=`<div class="stat"><b>${objects.length}</b><span>Objets</span></div><div class="stat"><b>${to}</b><span>À valider</span></div><div class="stat"><b>${ok}</b><span>Validés</span></div><div class="stat"><b>${co}</b><span>À corriger</span></div>`}
function nav(){let h='';for(const n of Object.keys(nets)){let r=objects.filter(o=>o.reseau===n&&dec(o)==='À valider').length;h+=`<button class="net ${n===current?'active':''}" data-net="${n}"><strong>${n}</strong><small>${nets[n]}</small><span class="pill ${r?'bad':'ok'}">${r}</span></button>`}$('#netNav').innerHTML=h;$$('#netNav .net').forEach(b=>b.onclick=()=>{current=b.dataset.net;render()})}
function filtered(){let q=$('#search').value.toLowerCase(),d=$('#decisionFilter').value,g=$('#groupFilter').value;return objects.filter(o=>o.reseau===current&&(!d||dec(o)===d)&&(!g||o.groupe_palette===g)&&(!q||[o.code,o.libelle,o.selection_attendue,o.type_mcd].join(' ').toLowerCase().includes(q)))}
function main(){stats();let arr=filtered(),by={};arr.forEach(o=>(by[o.groupe_palette]??=[]).push(o));let h=`<div class="net-head"><h2>${current} - ${nets[current]}</h2><p>${arr.length} objet(s) affiché(s).</p></div>`;for(const g in by)h+=`<h3 class="section-title">${g} · ${by[g].length}</h3><div class="cards">${by[g].map(card).join('')}</div>`;$('#main').innerHTML=h;$$('.card [data-action]').forEach(b=>b.onclick=()=>{let uid=b.closest('.card').dataset.uid;set(uid,{decision:b.dataset.action})});$$('.card [data-edit]').forEach(b=>b.onclick=()=>edit(b.closest('.card').dataset.uid))}
function card(o){let x=merged(o),c=dec(o)==='Validé'?'ok':dec(o)==='À corriger'?'warn':dec(o)==='Exclu'?'bad':cls(o.statut_selection);return`<article class="card ${c}" data-uid="${o.uid}"><div class="icon">${o.reseau}</div><div><div class="title">${esc(o.libelle)}</div><div class="code">${esc(o.code)}</div><div class="pills"><span class="pill ${cls(o.statut_selection)}">${o.statut_selection}</span><span class="pill ${cls(o.statut_dwg)}">${o.statut_dwg}</span><span class="pill">${o.famille_mcd}/${o.type_mcd}</span></div></div><div class="mini">SEL : <b>${esc(x.selection_attendue)}</b><br>DWG : ${esc(x.bloc_dwg||'-')}<br>ATTR : ${x.attrs.length}</div><div class="card-actions"><button data-action="Validé">Valider</button><button data-action="À corriger">Corriger</button><button data-action="Exclu">Exclure</button><button data-edit>Attributs / listes</button></div></article>`}
function edit(uid){selected=uid;let o=objects.find(x=>x.uid===uid),x=merged(o);tab('general');$('#dialogTitle').textContent=o.code+' · '+o.libelle;$('#dialogSub').textContent=o.reseau+' / '+o.groupe_palette+' / '+o.famille_mcd;$('#tab-general').innerHTML=`<div class="form-grid"><label>Décision<select id="eDec"><option>À valider</option><option>Validé</option><option>À corriger</option><option>Exclu</option></select></label><label>Sélection<input id="eSel" value="${esc(x.selection_attendue)}"></label><label>Calque<input id="eCal" value="${esc(x.calque)}"></label><label>Bloc DWG<input id="eDwg" value="${esc(x.bloc_dwg)}"></label><label class="full">Commentaire<textarea id="eCom">${esc(x.commentaire_validation||'')}</textarea></label></div><div class="actions"><button id="eSave" class="primary">Enregistrer</button></div>`;$('#eDec').value=dec(o);$('#eSave').onclick=()=>set(uid,{decision:$('#eDec').value,selection_attendue:$('#eSel').value,calque:$('#eCal').value,bloc_dwg:$('#eDwg').value,commentaire_validation:$('#eCom').value});drawAttrs(x);drawLists(x);$('#editDialog').showModal()}
function tab(t){$$('#editDialog .tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===t));$$('#editDialog .tab').forEach(x=>x.classList.toggle('active',x.id==='tab-'+t))}
function drawAttrs(x){$('#tab-attrs').innerHTML=`<div class="actions"><button id="addA">Ajouter attribut</button><button id="saveA" class="primary">Enregistrer attributs</button></div><div class="table-wrap"><table><thead><tr><th>Champ</th><th>Type</th><th>Libellé</th><th>Liste</th><th>Forcé</th><th></th></tr></thead><tbody id="ab">${x.attrs.map(row).join('')}</tbody></table></div>`;$('#addA').onclick=()=>$('#ab').insertAdjacentHTML('beforeend',row({champ:'',type_donnee:'Texte',libelle_attribut:'',liste_reference:'',valeur_forcee:''}));$('#saveA').onclick=()=>{let attrs=$$('#ab tr').map(tr=>Object.fromEntries($$('input',tr).map(i=>[i.dataset.k,i.value])));set(selected,{attrs,decision:'À corriger'});edit(selected)};$('#ab').onclick=e=>{if(e.target.dataset.del)e.target.closest('tr').remove()}}
function row(a){return`<tr><td><input data-k="champ" value="${esc(a.champ)}"></td><td><input data-k="type_donnee" value="${esc(a.type_donnee)}"></td><td><input data-k="libelle_attribut" value="${esc(a.libelle_attribut)}"></td><td><input data-k="liste_reference" value="${esc(a.liste_reference||'')}"></td><td><input data-k="valeur_forcee" value="${esc(a.valeur_forcee||'')}"></td><td><button data-del="1">Suppr.</button></td></tr>`}
function drawLists(x){let names=[...new Set(x.attrs.map(a=>a.liste_reference).filter(Boolean))];$('#tab-lists').innerHTML=names.length?names.map(n=>`<div class="list-card"><h3>${esc(n)}</h3><p>Liste partagée : toute modification sera utilisée partout où ce nom de liste est appelé.</p><textarea data-list="${esc(n)}" rows="8" style="width:100%">${esc((state.lists[n]||reg[n]||[]).join('\n'))}</textarea><div class="actions"><button data-save-list="${esc(n)}" class="primary">Enregistrer cette liste</button></div></div>`).join(''):'<p>Aucune liste appelée.</p>';$$('[data-save-list]').forEach(b=>b.onclick=()=>{let n=b.dataset.saveList;state.lists[n]=$(`[data-list="${CSS.escape(n)}"]`).value.split('\n').map(v=>v.trim()).filter(Boolean);save();alert('Liste enregistrée et partagée globalement.')})}
function exportJson(){let blob=new Blob([JSON.stringify({version:1,updatedAt:new Date().toISOString(),items:state.items,lists:state.lists,objects:objects.length},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='validation_palette_land2map.json';a.click();URL.revokeObjectURL(a.href)}
init();