const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const STORE='l2m_state_v4';let state=JSON.parse(localStorage.getItem(STORE)||'{"items":{}}'),current='AEP';
const nets={AEP:'Eau potable',EUS:'Eaux usées',EPL:'Eaux pluviales',UNI:'Unitaire',MLT:'Multiréseaux',ECL:'Éclairage public',BTA:'Basse tension A',HTA:'Haute tension A',HTB:'Haute tension B',TEL:'Télécom',CFA:'Courants faibles',GAZ:'Gaz',CHI:'Chimique',CHU:'Chauffage urbain',HYD:'Hydrocarbures',ARO:'Arrosage',SGN:'Signalisation',NDE:'Non déterminé',FRV:'Fourreau vide'};
const nb={AEP:23,EUS:17,EPL:17,UNI:17,MLT:15,ECL:23,BTA:23,HTA:23,HTB:22,TEL:21,CFA:21,GAZ:15,CHI:15,CHU:15,HYD:15,ARO:15,SGN:19,NDE:15,FRV:15};
const tpl=[['CANALISATION','Canalisation','Linéaires','troncon'],['BRANCHEMENT','Branchement','Linéaires','troncon'],['FOURREAU','Fourreau','Linéaires','troncon'],['REGARD_CIRCULAIRE','Regard circulaire','Ouvrages','ouvrage'],['REGARD_RECTANGULAIRE','Regard rectangulaire','Ouvrages','ouvrage'],['CHAMBRE_TIRAGE','Chambre tirage','Ouvrages','ouvrage'],['ARMOIRE','Armoire','Ouvrages','ouvrage'],['POSTE','Poste','Ouvrages','ouvrage'],['PUITS','Puits','Ouvrages','ouvrage'],['AVALOIR','Avaloir','Ouvrages','ouvrage'],['DEVERSOIR','Déversoir','Ouvrages','ouvrage'],['VANNE','Vanne','Équipements','equipement'],['PURGE','Purge','Équipements','equipement'],['VENTOUSE','Ventouse','Équipements','equipement'],['CLAPET','Clapet','Équipements','equipement'],['COFFRET','Coffret','Équipements','equipement'],['LUMINAIRE','Luminaire','Équipements','equipement'],['BORNE','Borne','Équipements','equipement'],['POTEAU','Poteau','Supports','support'],['APPUI','Appui','Supports','support'],['PLAQUE_CARREE','Plaque carrée','Affleurants','affleurant'],['PLAQUE_RONDE','Plaque ronde','Affleurants','affleurant'],['GRILLE_AVALOIR','Grille avaloir','Affleurants','affleurant']];
const objects=[];for(const n of Object.keys(nets)){for(let i=0;i<nb[n];i++){let t=tpl[i%tpl.length],code=n+'_'+t[0];objects.push({uid:code,reseau:n,code,libelle:t[1],groupe_palette:t[2],famille_mcd:t[3],type_mcd:t[0].toLowerCase(),selection_attendue:n.toLowerCase()+'_'+t[0].toLowerCase()+'_sel',statut_selection:'SEL MANQUANT',statut_icone:'ICONE A VERIFIER',statut_dwg:t[2]==='Linéaires'?'DWG NA':'DWG A VERIFIER',bloc_dwg:t[2]==='Linéaires'?'':t[0]+'.dwg',calque:'ECA_RSX_'+n+'_*'});}}
function save(){localStorage.setItem(STORE,JSON.stringify(state));}function dec(o){return state.items[o.uid]?.decision||'À valider';}function cls(v){v=String(v||'').toLowerCase();return v.includes('valid')||v.includes('ok')?'ok':v.includes('corriger')||v.includes('verifier')?'warn':v.includes('manquant')||v.includes('exclu')?'bad':''}function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function init(){let groups=[...new Set(objects.map(o=>o.groupe_palette))];$('#groupFilter').innerHTML='<option value="">Tous groupes</option>'+groups.map(g=>'<option>'+g+'</option>').join('');['search','decisionFilter','groupFilter'].forEach(id=>$('#'+id).addEventListener(id==='search'?'input':'change',main));$('#exportBtn').onclick=exportJson;$('#syncBtn').onclick=()=>alert('Export JSON puis commit du fichier dans Git.');render();}
function render(){stats();nav();main();}function stats(){let ok=0,co=0,to=0;objects.forEach(o=>dec(o)==='Validé'?ok++:dec(o)==='À corriger'?co++:dec(o)==='Exclu'?0:to++);$('#stats').innerHTML=`<div class="stat"><b>${objects.length}</b><span>Objets</span></div><div class="stat"><b>${to}</b><span>À valider</span></div><div class="stat"><b>${ok}</b><span>Validés</span></div><div class="stat"><b>${co}</b><span>À corriger</span></div>`}
function nav(){let h='';for(const n of Object.keys(nets)){let r=objects.filter(o=>o.reseau===n&&dec(o)==='À valider').length;h+=`<button class="net ${n===current?'active':''}" data-net="${n}"><strong>${n}</strong><small>${nets[n]}</small><span class="pill ${r?'bad':'ok'}">${r}</span></button>`}$('#netNav').innerHTML=h;$$('#netNav .net').forEach(b=>b.onclick=()=>{current=b.dataset.net;render();});}
function filtered(){let q=$('#search').value.toLowerCase(),d=$('#decisionFilter').value,g=$('#groupFilter').value;return objects.filter(o=>o.reseau===current&&(!d||dec(o)===d)&&(!g||o.groupe_palette===g)&&(!q||[o.code,o.libelle,o.selection_attendue,o.type_mcd].join(' ').toLowerCase().includes(q)));}
function main(){stats();let arr=filtered(),by={};arr.forEach(o=>(by[o.groupe_palette]??=[]).push(o));let h=`<div class="net-head"><h2>${current} - ${nets[current]}</h2><p>${arr.length} objet(s) affiché(s).</p></div>`;for(const g in by)h+=`<h3 class="section-title">${g} · ${by[g].length}</h3><div class="cards">${by[g].map(card).join('')}</div>`;$('#main').innerHTML=h;$$('.card [data-action]').forEach(b=>b.onclick=()=>{let uid=b.closest('.card').dataset.uid;state.items[uid]={...(state.items[uid]||{}),decision:b.dataset.action};save();render();});$$('.card [data-edit]').forEach(b=>b.onclick=()=>edit(b.closest('.card').dataset.uid));}
function card(o){let c=dec(o)==='Validé'?'ok':dec(o)==='À corriger'?'warn':dec(o)==='Exclu'?'bad':cls(o.statut_selection);return`<article class="card ${c}" data-uid="${o.uid}"><div class="icon">${o.reseau}</div><div><div class="title">${esc(o.libelle)}</div><div class="code">${esc(o.code)}</div><div class="pills"><span class="pill ${cls(o.statut_selection)}">${o.statut_selection}</span><span class="pill ${cls(o.statut_dwg)}">${o.statut_dwg}</span><span class="pill">${o.famille_mcd}/${o.type_mcd}</span></div></div><div class="mini">SEL : <b>${esc(o.selection_attendue)}</b><br>DWG : ${esc(o.bloc_dwg||'-')}</div><div class="card-actions"><button data-action="Validé">Valider</button><button data-action="À corriger">Corriger</button><button data-action="Exclu">Exclure</button><button data-edit>Modifier</button></div></article>`}
function edit(uid){let o=objects.find(x=>x.uid===uid),s=state.items[uid]||{};let com=prompt(o.code+'\nCommentaire / correction :',s.commentaire_validation||'');if(com!==null){state.items[uid]={...s,decision:'À corriger',commentaire_validation:com};save();render();}}
function exportJson(){let blob=new Blob([JSON.stringify({version:1,items:state.items,objects:objects.length},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='validation_palette_land2map.json';a.click();URL.revokeObjectURL(a.href)}
init();