const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s)),C=window.L2M_CAT,KEY='l2m_v21';let cur='AEP',selObj=null,st=JSON.parse(localStorage.getItem(KEY)||'{}');
function pts(n){return (C.pts[n]||'REGARD_CIRCULAIRE REGARD_RECTANGULAIRE CHAMBRE_TECHNIQUE PLAQUE_RONDE BORNE REPERE EQUIPEMENT_SPECIFIQUE RAS').split(' ')}
function fam(x){if(['SUPPORT','PI','SUPPORT_2','MAT','CANDELABRE_SIMPLE','CANDELABRE_MULTIPLE','PANNEAU'].includes(x))return['Supports','support'];if(x.includes('PLAQUE')||x.includes('TAMPON')||x.includes('GRILLE')||x=='AVALOIR')return['Affleurants','affleurant'];if(x.includes('REGARD')||x.includes('CHAMBRE')||x.includes('POSTE')||x.includes('SEPARATEUR')||x=='CUVE'||x=='DEVERSOIR')return['Ouvrages','ouvrage'];return['Equipements','equipement']}
function pref(f,t){if(t=='cable')return'che';if(t=='fourreau')return'fou';if(t=='branchement')return'brt';if(['canalisation','troncon','conduite'].includes(t))return'trc';return{ouvrage:'ouv',affleurant:'afl',equipement:'eqp',support:'sup'}[f]||'obj'}
function A(c,t,l,li='',val='',vis=true,fo=false,obl=false,exp=true){return{c,t,l,li,val,vis,fo,obl,exp}}
function attrs(n,f,t,F={}){let p=pref(f,t),isLin=f=='troncon';let a=[A('id','UUID','Identifiant','','',false,false,true,true),A('calque','Texte','Calque AutoCAD','',F.calque||('ECA_RSX_'+n+'_'+t.toUpperCase()),false,true,true,true),A(p+'_type','Texte','Type objet','',t,false,true,true,true),A(p+'_mlev','Liste','Mode levé','LST_MODE_LEVE','',true,false,true,true),A(p+'_classe','Liste','Classe précision','LST_CLASSE_PRECISION',F.clas||'',!F.clas,!!F.clas,isLin,true),A(p+'_etat','Liste','État','LST_ETAT_RESEAU',F.etat||'',!F.etat,!!F.etat,false,true),A(p+'_pose','Liste','Mode de pose','LST_POSE',F.pose||'',!F.pose,!!F.pose,false,true),A('x','Nombre','Coordonnée X','','',false,false,true,true),A('y','Nombre','Coordonnée Y','','',false,false,true,true),A('z','Nombre','Altitude Z','','',true,false,false,true),A('gnss_hdop','Nombre','GNSS HDOP','','',false),A('gnss_vdop','Nombre','GNSS VDOP','','',false),A('gnss_pdop','Nombre','GNSS PDOP','','',false),A('gnss_fix','Liste','Solution GNSS','LST_GNSS_FIX','',false),A('gnss_prec','Nombre','Précision GNSS','','',false),A('date_leve','Date','Date levé','','',false),A('src_leve','Texte','Source levé','','',false),A('matricule','Texte','Matricule point'),A(p+'_obs','Texte','Observation')];if(!isLin)a.push(A('acad_ech','Nombre','Échelle AutoCAD','','',false),A('acad_xech','Nombre','Échelle X AutoCAD','','',false),A('acad_yech','Nombre','Échelle Y AutoCAD','','',false),A('acad_rot','Nombre','Rotation AutoCAD','','',false));return a}
function lib(s){return s.toLowerCase().replaceAll('_',' ').replace(/^./,c=>c.toUpperCase())}let O=[];function add(n,code,g,f,t,F={},v=''){O.push({n,code,lib:lib(code.replace(n+'_','')),g,f,t,v,sel:n.toLowerCase()+'_'+t+(v?'_'+v.toLowerCase().replaceAll(' ','_'):'')+'_sel',attrs:attrs(n,f,t,F)})}
for(const n of C.nets){for(const b of C.lin[n]){let t=b.toLowerCase();add(n,n+'_'+b,'Lineaires','troncon',t);add(n,n+'_'+b+'_CLASSE_A','Lineaires','troncon',t,{clas:'A'},'Classe A');add(n,n+'_'+b+'_CLASSE_B','Lineaires','troncon',t,{clas:'B'},'Classe B');add(n,n+'_'+b+'_CLASSE_C','Lineaires','troncon',t,{clas:'C'},'Classe C');add(n,n+'_'+b+'_ABANDONNE','Lineaires','troncon',t,{etat:'Abandonné'},'Abandonné');if(C.aerienOK.includes(n))add(n,n+'_'+b+'_AERIEN','Lineaires','troncon',t,{pose:'Aérien'},'Aérien')}for(const p of pts(n)){let f=fam(p);add(n,n+'_'+p,f[0],f[1],p.toLowerCase())}}
function cfg(o){return st[o.code]||{}}function files(o){return cfg(o).files||{}}function aa(o){let m=cfg(o).a||{};return o.attrs.map(x=>Object.assign({},x,m[x.c]||{}))}function deci(o){return cfg(o).d||'A valider'}function persist(){localStorage.setItem(KEY,JSON.stringify(st));stamp()}function stamp(){stats.innerHTML='<div class=stat><b>'+O.length+'</b><div class=muted>Objets</div><div class=muted>Enregistré localement : '+new Date().toLocaleTimeString()+'</div></div>'}
function put(c,a,k,v){st[c]=st[c]||{};st[c].a=st[c].a||{};st[c].a[a]=st[c].a[a]||{};st[c].a[a][k]=v;persist();if(selObj&&selObj.code==c)openPop(c);draw()}function setFile(c,k,v){st[c]=st[c]||{};st[c].files=st[c].files||{};st[c].files[k]=v;persist();if(selObj&&selObj.code==c)openPop(c);draw()}function setD(c,d){st[c]=st[c]||{};st[c].d=d;persist();draw()}
