const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s)),C=window.L2M_CAT,KEY='l2m_v21';let cur='AEP',selObj=null,st=JSON.parse(localStorage.getItem(KEY)||'{}');
function pts(n){let s=(C.pts&&C.pts[n])||'';return s.trim()?s.trim().split(/\s+/):[]}
function baseFam(x){if(['SUPPORT','APPUI','PI','POTEAU_INCENDIE_PI','PYLONE','PORTIQUE','MAT','CANDELABRE_SIMPLE','CANDELABRE_MULTIPLE','PANNEAU'].includes(x))return['Supports','support'];if(x.includes('BOUCHE')||x.includes('GRILLE')||x=='AVALOIR'||x=='COFFRET'||x=='BORNE'||x=='BOITIER')return['Affleurants','affleurant'];if(x.includes('REGARD')||x.includes('CHAMBRE')||x.includes('POSTE')||x.includes('SEPARATEUR')||x=='CUVE'||x=='DEVERSOIR'||x=='BASSIN_RETENTION'||x=='PUISARD'||x=='TETE_BUSE'||x=='EXUTOIRE')return['Ouvrages','ouvrage'];return['Equipements','equipement']}
function metaOf(n,x){return (C.meta&&C.meta[n]&&C.meta[n][x])||{}}
function fam(n,x){let m=metaOf(n,x),b=baseFam(x);return[m.g||b[0],m.f||b[1]]}
function pref(f,t){if(t=='cable')return'che';if(t=='fourreau')return'fou';if(t=='branchement')return'brt';if(['canalisation','troncon','conduite'].includes(t))return'trc';return{ouvrage:'ouv',affleurant:'afl',equipement:'eqp',support:'sup'}[f]||'obj'}
function na(s){return String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9_]/g,'_').replace(/_+/g,'_').replace(/^_|_$/g,'').toLowerCase()}
function A(c,t,l,li='',val='',vis=true,fo=false,obl=false,exp=true){return{c:na(c),t,l,li:li?na(li):'',val,vis,fo,obl,exp}}
function specList(n){return C.vals['lst_eqp_spec_'+na(n)]?'lst_eqp_spec_'+na(n):'lst_eqp_spec'}
function listField(p,li,i){li=na(li);if(li.includes('vnn_fonction'))return'eqp_fonc';if(li.includes('vnn_type'))return'eqp_vtyp';if(li.includes('bac_usage')||li.includes('bcg_usage'))return p+'_usage';return p+'_lst'+(i+1)}
function listLabel(li){return na(li).replace(/^lst_/,'').replaceAll('_',' ').toLowerCase().replace(/^./,c=>c.toUpperCase())}
function attrs(n,f,t,F={},M={}){let p=pref(f,t),isLin=f=='troncon',isSpec=t=='equipement_specifique',lists=(M.li||'').split(';').filter(Boolean);let a=[A('id','UUID','Identifiant','','',false,false,true,true),A('calque','Texte','Calque AutoCAD','',F.calque||('ECA_RSX_'+n+'_'+t.toUpperCase()),false,true,true,true),A(p+'_type','Texte','Type objet','',isSpec?'specifique':t,false,true,true,true)];
if(isSpec){a.push(A('eqp_spec','Liste','Equipement specifique',specList(n),'',true,false,true,true));lists=lists.filter(li=>!na(li).includes('lst_eqp_spec'))}
lists.forEach((li,i)=>a.push(A(listField(p,li,i).slice(0,10),'Liste',listLabel(li),li,'',true,false,false,true)));
if(isLin)a.push(A('mdetec1','Liste','Methode detection 1','lst_meth_detec','',true,false,true,true),A('mdetec2','Liste','Methode detection 2','lst_meth_detec','',true,false,false,true));
else{a.push(A(p+'_mlev','Liste','Mode leve','lst_mode_leve','',true,false,true,true),A('x','Nombre','Coordonnee X','','',false,false,true,true),A('y','Nombre','Coordonnee Y','','',false,false,true,true),A('z','Nombre','Altitude Z','','',true,false,false,true),A('date_leve','Date','Date leve','','',false,false,false,true));if(f!='equipement')a.push(A('acad_ech','Nombre','Echelle AutoCAD','','',false,false,false,true),A('acad_xech','Nombre','Echelle X AutoCAD','','',false,false,false,true),A('acad_yech','Nombre','Echelle Y AutoCAD','','',false,false,false,true),A('acad_rot','Nombre','Rotation AutoCAD','','',false,false,false,true));}
a.push(A(p+'_classe','Liste','Classe precision','lst_classe_precision',F.clas||'',!F.clas,!!F.clas,isLin,true),A(p+'_etat','Liste','Etat','lst_etat_reseau',F.etat||'',!F.etat,!!F.etat,false,true),A(p+'_pose','Liste','Mode de pose','lst_pose',F.pose||'',!F.pose,!!F.pose,false,true),A('matricule','Texte','Matricule point'),A(p+'_obs','Texte','Observation'));
return a}
function lib(s){return s.toLowerCase().replaceAll('_',' ').replace(/^./,c=>c.toUpperCase())}let O=[];function add(n,code,g,f,t,F={},v='',M={}){O.push({n,code,lib:lib(code.replace(n+'_','')),g,f,t,v,meta:M,sel:n.toLowerCase()+'_'+t+(v?'_'+v.toLowerCase().replaceAll(' ','_'):'')+'_sel',attrs:attrs(n,f,t,F,M)})}
for(const n of C.nets){let l=C.lin[n]||[];for(const b of l){let t=b.toLowerCase();add(n,n+'_'+b,'Lineaires','troncon',t);add(n,n+'_'+b+'_CLASSE_A','Lineaires','troncon',t,{clas:'A'},'Classe A');add(n,n+'_'+b+'_CLASSE_B','Lineaires','troncon',t,{clas:'B'},'Classe B');add(n,n+'_'+b+'_CLASSE_C','Lineaires','troncon',t,{clas:'C'},'Classe C');add(n,n+'_'+b+'_ABANDONNE','Lineaires','troncon',t,{etat:'Abandonne'},'Abandonne');if(C.aerienOK.includes(n))add(n,n+'_'+b+'_AERIEN','Lineaires','troncon',t,{pose:'Aerien'},'Aerien')}for(const p of pts(n)){let m=metaOf(n,p),ff=fam(n,p);add(n,n+'_'+p,ff[0],ff[1],p.toLowerCase(),{},'',m)}}
if(!O.some(o=>o.code=='AEP_COMPTEUR'))add('AEP','AEP_COMPTEUR','Equipements','equipement','compteur');
if(!O.some(o=>o.code=='AEP_ARMOIRE'))add('AEP','AEP_ARMOIRE','Equipements','equipement','armoire');
(function(){const cat=window['L2M_CAT'];cat['vals']=cat['vals']||{};Object.keys(cat['vals']).forEach(function(k){let nk=na(k);if(nk!==k&&!cat['vals'][nk])cat['vals'][nk]=cat['vals'][k]});cat['vals']['lst_can_mat']=['pvc','pvca','pehd','acier','be','inc'];cat['vals']['lst_etat_reseau']=(cat['vals']['lst_etat_reseau']||cat['vals']['LST_ETAT_RESEAU']||[]).filter(function(v){return !String(v).toLowerCase().startsWith('proj')});cat['vals']['lst_meth_detec']=['DEM','Aiguillage','Sonde','Georadar','Electromagnetique','Radiodetection','Acoustique','Ouverture de fouille','Report plan','Non detecte','Inconnu'];cat['vals']['lst_tam_etat']=['Tampon sous enrobe','Tampon bloque','Tampon voile','Tampon casse','Affaissement voirie'];cat['vals']['lst_descend']=['Pas de descenderie','Echelon manquant','Crosse manquante'];function h(o,c){return o['attrs'].some(function(a){return a['c']==na(c)})}function ad(o,a){if(!h(o,a['c']))o['attrs'].push(a)}
O.forEach(function(o){var r=o['t'].indexOf('regard')>=0,af=o['f']=='affleurant',acc=r||o['t'].indexOf('chambre')>=0||o['t'].indexOf('boite_branchement')>=0,p=pref(o['f'],o['t']);o['attrs']=o['attrs'].map(function(a){a['c']=na(a['c']);a['li']=a['li']?na(a['li']):'';return a}).filter(function(a){return ['gnss_fix','gnss_prec','src_leve','tam_enrob'].indexOf(a['c'])<0 && (o['f']!='equipement' || !/^acad_/.test(a['c']))});if(o['f']=='troncon'){o['attrs']=o['attrs'].filter(function(a){return ['x','y','z','date_leve','gnss_hdop','gnss_vdop','gnss_pdop',p+'_mlev'].indexOf(a['c'])<0});ad(o,A('mdetec1','Liste','Methode detection 1','lst_meth_detec','',true,false,true,true));ad(o,A('mdetec2','Liste','Methode detection 2','lst_meth_detec','',true,false,false,true));if(o['n']=='AEP'&&o['t']=='canalisation')ad(o,A('trc_mat','Liste','Materiau canalisation','lst_can_mat','',true,false,false,true));}
if(r||af)o['attrs']=o['attrs'].filter(function(a){return a['c']!=p+'_pose'});if(acc){ad(o,A('rad_prof','Nombre','Profondeur radier','','',true,false,false,true));ad(o,A('descend','Liste','Descenderie','lst_descend','',true,false,false,true));}if(r||af)ad(o,A('tam_etat','Liste','Etat tampon','lst_tam_etat','',true,false,false,true));});})();
function cfg(o){return st[o.code]||{}}function files(o){return cfg(o).files||{}}function aa(o){let m=cfg(o).a||{};return o.attrs.map(x=>Object.assign({},x,m[x.c]||{}))}function deci(o){return cfg(o).d||'A valider'}function persist(){localStorage.setItem(KEY,JSON.stringify(st));stamp()}function stamp(){stats.innerHTML='<div class=stat><b>'+O.length+'</b><div class=muted>Objets</div><div class=muted>Enregistre localement : '+new Date().toLocaleTimeString()+'</div></div>'}
function put(c,a,k,v){st[c]=st[c]||{};st[c].a=st[c].a||{};st[c].a[a]=st[c].a[a]||{};st[c].a[a][k]=v;persist();if(selObj&&selObj.code==c)openPop(c);draw()}function setFile(c,k,v){st[c]=st[c]||{};st[c].files=st[c].files||{};st[c].files[k]=v;persist();if(selObj&&selObj.code==c)openPop(c);draw()}function setD(c,d){st[c]=st[c]||{};st[c].d=d;persist();draw()}