(function(){
  if(!window.O||!window.C)return;
  window.L2M_VIEW=window.L2M_VIEW||'palette';
  function esc2(s){return typeof esc==='function'?esc(s):String(s).replace(/[&<>"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]})}
  function attrVal(o,c){let a=(aa(o)||[]).find(function(x){return x.c===c});return a&&(a.val||'')}
  function coucheMCD(o){
    if(!o)return'';
    if(o.n==='GEN'||/^GEN_/.test(String(o.code||'')))return'ECA_GEN_ANNOTATION';
    let n=o.n,t=String(o.t||''),code=String(o.code||'');
    if(/regard_(circulaire|rectangulaire)/.test(t)||/_(REGARD_CIRCULAIRE|REGARD_RECTANGULAIRE)$/.test(code))return'ECA_RSX_'+n+'_REGARD';
    if(/^chambre($|_tirage$|_technique$|_jonction$)/.test(t)||/_(CHAMBRE|CHAMBRE_TIRAGE|CHAMBRE_TECHNIQUE|CHAMBRE_JONCTION)$/.test(code))return'ECA_RSX_'+n+'_CHAMBRE';
    if(t==='equipement_specifique'||/_EQUIPEMENT_SPECIFIQUE$/.test(code))return'ECA_RSX_'+n+'_EQUIPEMENT_SPECIFIQUE';
    return attrVal(o,'calque')||('ECA_RSX_'+n+'_'+String(t||code.replace(n+'_','')).toUpperCase());
  }
  window.coucheMCD=coucheMCD;
  function layerMap(arr){let m={};(arr||O).forEach(function(o){let l=coucheMCD(o);(m[l]??=[]).push(o)});return m}
  function isShared(o){return (layerMap()[coucheMCD(o)]||[]).length>1}
  function fileInfo(o){try{return typeof ffiles==='function'?ffiles(o):(files(o)||{})}catch(e){return files(o)||{}}}
  function listOK(o){return (aa(o)||[]).filter(function(a){return a.li&&!C.vals[a.li]}).length===0}
  function needsBloc(o){return o.f!=='troncon'}
  function status(o){let f=fileInfo(o),bloc=!needsBloc(o)||!!f.bloc_dwg,ico=!!(f.icone_palette||f.icone_bloc),sel=!!o.sel,lst=listOK(o);return bloc&&ico&&sel&&lst?'Prêt':'Incomplet'}
  function filtered(){let s=q.value.toLowerCase();return O.filter(function(o){let f=fileInfo(o),lay=coucheMCD(o);return o.n==cur&&(!grp.value||o.g==grp.value)&&(!dec.value||deci(o)==dec.value)&&(!s||[o.code,o.lib,o.sel,lay,f.bloc_dwg,f.icone_palette,f.icone_bloc,status(o)].join(' ').toLowerCase().includes(s))})}
  function addToggle(){let bar=document.querySelector('.bar');if(!bar||document.getElementById('layerViewBtn'))return;let b=document.createElement('button');b.id='layerViewBtn';b.className='layerToggle';b.textContent='Vue couches MCD';b.onclick=function(){window.L2M_VIEW=window.L2M_VIEW==='layers'?'palette':'layers';b.textContent=window.L2M_VIEW==='layers'?'Vue palette':'Vue couches MCD';draw()};bar.appendChild(b)}
  function mcdAudit(){let all=layerMap(),layers=Object.keys(all),shared=layers.filter(function(k){return all[k].length>1}).length,btn=O.length,reg=layers.filter(function(k){return /_REGARD$/.test(k)}).length,ch=layers.filter(function(k){return /_CHAMBRE$/.test(k)}).length,gen=(all.ECA_GEN_ANNOTATION||[]).length;return '<div class=mcdAudit><div><b>'+layers.length+'</b><span class=muted>Couches MCD</span></div><div><b>'+btn+'</b><span class=muted>Boutons</span></div><div><b>'+shared+'</b><span class=muted>Couches partagées</span></div><div><b>'+reg+'</b><span class=muted>Regroupements REGARD</span></div><div><b>'+ch+'</b><span class=muted>Regroupements CHAMBRE</span></div><div><b>'+gen+'</b><span class=muted>Boutons GEN annotation</span></div></div>'}
  let oldStamp=stamp;stamp=function(){let v=(window.L2M_MANIFEST&&window.L2M_MANIFEST.version)||'v48';stats.innerHTML='<div class=stat><b>'+O.length+'</b><span class=versionpill>'+v+'</span><div class=muted>Objets</div><div class=muted>Enregistré localement : '+new Date().toLocaleTimeString()+'</div></div>'+(typeof dashboard==='function'?dashboard():'')+mcdAudit()}
  let oldRender=render;render=function(){addToggle();oldRender();addToggle();}
  function badge(txt,cls){return '<span class="badge '+(cls||'info')+'">'+txt+'</span>'}
  card=function(o){let ar=aa(o),f=fileInfo(o),vis=ar.filter(x=>x.vis).length,fo=ar.filter(x=>x.fo).length,stt=status(o),layer=coucheMCD(o),shared=isShared(o);let cls=deci(o)=='Valide'?'ready':deci(o)=='A corriger'?'todo':deci(o)=='Ignoré'?'bad':(stt==='Prêt'?'ready':'incomplete');let badges='<div class=badgebar>'+badge(o.f=='troncon'?'Linéaire':'Ponctuel')+badge(shared?'Couche partagée':'Couche unique',shared?'info':'ok')+badge('Bloc '+(!needsBloc(o)?'non requis':(f.bloc_dwg||'manquant')),(!needsBloc(o)||f.bloc_dwg)?'ok':'bad')+badge('Icône',f.icone_palette||f.icone_bloc?'ok':'bad')+badge('Sélection',o.sel?'ok':'bad')+badge('Listes',listOK(o)?'ok':'bad')+(ar.some(a=>a.c==='photo')?badge('Photo','info'):'')+(fo?badge('Forcé '+fo,'info'):'')+badge(stt,stt==='Prêt'?'ok':'warn')+'</div>';return '<article class="card '+cls+'"><b>'+esc2(o.lib)+'</b><div class=code>'+esc2(o.code)+'</div>'+badges+'<span class=pill>'+o.f+'/'+o.t+'</span>'+(o.v?'<span class=pill>'+esc2(o.v)+'</span>':'')+'<div class=mcdline>COUCHE <span class=mcdLayer>'+esc2(layer)+'</span></div><div class=mutedline>SEL '+esc2(o.sel)+'<br>ATTR '+ar.length+' - visibles '+vis+' - forcés '+fo+'<br>DWG '+esc2(f.bloc_dwg||'-')+'<br>ICO '+esc2(f.icone_palette||f.icone_bloc||'-')+'</div><button data-d="Valide" data-c="'+o.code+'">Valider</button><button data-d="A corriger" data-c="'+o.code+'">Corriger</button><button data-d="Ignoré" data-c="'+o.code+'">Ignorer</button><button data-open="'+o.code+'">Attributs / listes</button></article>'}
  let oldOpenPop=openPop;openPop=function(code){oldOpenPop(code);let o=O.find(x=>x.code==code);if(o){ms.innerHTML=esc2(o.code+' | '+o.g+' | '+o.sel)+'<br>COUCHE MCD <span class=mcdLayer>'+esc2(coucheMCD(o))+'</span>'}}
  function drawPalette(){let arr=filtered(),by={};arr.forEach(o=>(by[o.g]??=[]).push(o));main.innerHTML='<div class=head><b>'+cur+' - '+(C.names[cur]||cur)+'</b> <small>'+arr.length+' objets affichés</small></div>'+Object.entries(by).map(([g,a])=>'<h3>'+g+' '+a.length+'</h3><div class=cards>'+a.map(card).join('')+'</div>').join('');bind();stamp()}
  function drawLayers(){let arr=filtered(),m=layerMap(arr);main.innerHTML='<div class=head><b>'+cur+' - Vue couches MCD</b> <small>'+Object.keys(m).length+' couches / '+arr.length+' boutons</small></div>'+Object.entries(m).sort().map(function(e){let layer=e[0],a=e[1];return '<section class="layerCard '+(a.length>1?'sharedLayer':'')+'"><h3><span class=mcdLayer>'+esc2(layer)+'</span> <small>'+a.length+' bouton(s)</small></h3><div class=layerBtns>'+a.map(function(o){return '<div class=layerBtn><b>'+esc2(o.code)+'</b><span class=layerMeta>'+esc2(o.lib)+'<br>SEL '+esc2(o.sel)+'<br>'+esc2(o.g)+' / '+esc2(o.f)+' / '+esc2(o.t)+'</span><br><button data-open="'+o.code+'">Ouvrir</button></div>'}).join('')+'</div></section>'}).join('');bind();stamp()}
  function bind(){$$('[data-open]').forEach(b=>b.onclick=()=>openPop(b.dataset.open));$$('[data-d]').forEach(b=>b.onclick=()=>setD(b.dataset.c,b.dataset.d))}
  draw=function(){window.L2M_VIEW==='layers'?drawLayers():drawPalette()}
  let oldPatch=patch;patch=function(o){let p=oldPatch(o);p.couche_mcd=coucheMCD(o);p.couche_partagee=isShared(o);return p}
  expJSON=function(){deliver('land2map_validation_v48.json',JSON.stringify({version:'v48',date:new Date().toISOString(),objets:O.map(patch)},null,2))}
  expCSV=function(){let rows=[['reseau','groupe_palette','code_bouton','libelle_bouton','selection','couche_mcd','couche_partagee','geometrie','bloc_dwg','icone_palette','icone_bloc','champ','type','liste','visible','force','obligatoire','exportable','valeur_forcee']];O.forEach(o=>aa(o).forEach(a=>{let f=fileInfo(o);rows.push([o.n,o.g,o.code,o.lib,o.sel,coucheMCD(o),isShared(o),o.f=='troncon'?'Ligne':'Point',f.bloc_dwg||'',f.icone_palette||'',f.icone_bloc||'',a.c,a.t,a.li,a.vis,a.fo,a.obl,a.exp,a.val||''])}));deliver('land2map_validation_v48.csv',rows.map(r=>r.map(x=>'"'+String(x).replaceAll('"','""')+'"').join(';')).join('\n'))}
  if(window.json)json.onclick=expJSON;if(window.csv)csv.onclick=expCSV;render();
})();