(function(){
if(!window.O||!window.C)return;
window.L2M_VIEW=window.L2M_VIEW||'palette';
function E(s){return typeof esc==='function'?esc(s):String(s).replace(/[&<>"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]})}
function typeCode(o){var t=String(o.t||''),c=String(o.code||'');if(/regard_(circulaire|rectangulaire)/.test(t)||/_(REGARD_CIRCULAIRE|REGARD_RECTANGULAIRE)$/.test(c))return'reg';if(/^chambre($|_tirage$|_technique$|_jonction$)/.test(t)||/_(CHAMBRE|CHAMBRE_TIRAGE|CHAMBRE_TECHNIQUE|CHAMBRE_JONCTION)$/.test(c))return'chb';if(t==='equipement_specifique'||/_EQUIPEMENT_SPECIFIQUE$/.test(c))return'eqs';var m={canalisation:'can',conduite:'can',troncon:'trc',branchement:'brt',cable:'cbl',fourreau:'fou',armoire:'arm',coffret:'cof',vanne:'van',vanne_gaz:'vga',bouche_cle:'bcl',bouche_cle_gaz:'bcg',fontaine:'fon',captage:'cpt',reservoir:'rsv',station_traitement:'stt',poste_pompage:'pmp',poste_relevage:'prv',poste_livraison_gaz:'plg',poste:'pst',transformateur:'trf',arroseur:'arr',cuve:'cuv',grille:'gri',avaloir:'avl',grille_avaloir:'gav',boite_branchement:'boi',bassin_retention:'bas',exutoire:'exu',puisard:'pui',tete_buse:'tbu',separateur_hydrocarbures:'sep',point_depotage:'dep',candelabre_simple:'cds',candelabre_multiple:'cdm',luminaire:'lum',mat:'mat',totem_lumineux:'tot',borne:'bor',boitier:'bot',support:'sup',ras:'ras',pylone:'pyl',portique:'por',boucle_detection:'bde',controleur_carrefour:'ctl',feu_tricolore:'feu',radar_pedagogique:'rad'};return (m[t]||String(t||c.replace((o.n||'')+'_','')).toLowerCase().replace(/[^a-z0-9]/g,'').slice(0,6)||'obj')}
function coucheMCD(o){if(!o)return'';if(o.n==='GEN'||/^GEN_/.test(String(o.code||'')))return'gen_ano';var n=String(o.n||'xxx').toLowerCase().slice(0,3);return (n+'_'+typeCode(o)).slice(0,10)}
window.coucheMCD=coucheMCD;
function map(a){var m={};(a||O).forEach(function(o){var l=coucheMCD(o);(m[l]=m[l]||[]).push(o)});return m}
function shared(o){return(map()[coucheMCD(o)]||[]).length>1}
function ff(o){try{return typeof ffiles==='function'?ffiles(o):(files(o)||{})}catch(e){return files(o)||{}}}
function flt(){var s=q.value.toLowerCase();return O.filter(function(o){var f=ff(o),lay=coucheMCD(o);return o.n==cur&&(!grp.value||o.g==grp.value)&&(!dec.value||deci(o)==dec.value)&&(!s||[o.code,o.lib,o.sel,lay,f.bloc_dwg,f.icone_palette,f.icone_bloc].join(' ').toLowerCase().includes(s))})}
function bind(){$$('[data-open]').forEach(function(b){b.onclick=function(){openPop(b.dataset.open)}});$$('[data-d]').forEach(function(b){b.onclick=function(){setD(b.dataset.c,b.dataset.d)}})}
function attachBtn(){var b=document.getElementById('layerViewBtn2');if(!b)return;b.onclick=function(){window.L2M_VIEW=window.L2M_VIEW==='layers'?'palette':'layers';this.textContent=window.L2M_VIEW==='layers'?'Vue palette':'Vue couches MCD';draw()}}
function tools(){if(!document.getElementById('mcdTools')){var s=document.createElement('section');s.id='mcdTools';s.className='mcdTools';s.innerHTML='<button id="layerViewBtn2">Vue couches MCD</button><span class="hint">couche_mcd visible ci-dessous, en minuscules, 10 caractères max. Exemple : aep_reg, aep_chb, gen_ano.</span>';document.querySelector('.bar').insertAdjacentElement('afterend',s)}attachBtn()}
var oldStamp=stamp;stamp=function(){oldStamp();var m=map(),ks=Object.keys(m),sh=ks.filter(function(k){return m[k].length>1}).length,reg=ks.filter(function(k){return/_reg$/.test(k)}).length,ch=ks.filter(function(k){return/_chb$/.test(k)}).length,gen=(m.gen_ano||[]).length,bad=ks.filter(function(k){return k.length>10||k!==k.toLowerCase()||/[^a-z0-9_]/.test(k)}).length;stats.innerHTML+='<div class=stat><b>Audit couches MCD</b><div class=mcdAudit><div><b>'+ks.length+'</b><span class=muted>Couches</span></div><div><b>'+sh+'</b><span class=muted>Partagées</span></div><div><b>'+reg+'</b><span class=muted>Regards</span></div><div><b>'+ch+'</b><span class=muted>Chambres</span></div><div><b>'+gen+'</b><span class=muted>gen_ano</span></div><div><b>'+bad+'</b><span class=muted>Non conformes</span></div></div></div>'}
var oldCard=card;card=function(o){var h=oldCard(o),lay=coucheMCD(o),tag=shared(o)?'couche_partagee':'couche_unique',warn=(lay.length>10||lay!==lay.toLowerCase()||/[^a-z0-9_]/.test(lay))?' mcdWarn':'';h=h.replace('<div class=code>'+o.code+'</div>','<div class=code>'+o.code+'</div><div class=mcdline>couche_mcd <span class="mcdLayer'+warn+'">'+E(lay)+'</span> <span class="badge info">'+tag+'</span></div>');return h}
var oldOpen=openPop;openPop=function(code){oldOpen(code);var o=O.find(function(x){return x.code==code});if(o)ms.innerHTML=E(o.code+' | '+o.g+' | '+o.sel)+'<br>couche_mcd <span class=mcdLayer>'+E(coucheMCD(o))+'</span>'}
var oldDraw=draw;draw=function(){if(window.L2M_VIEW!=='layers'){oldDraw();tools();return}var a=flt(),m=map(a);main.innerHTML='<div class=head><b>'+cur+' - Vue couches MCD</b> <small>'+Object.keys(m).length+' couches / '+a.length+' boutons</small></div>'+Object.entries(m).sort().map(function(e){var l=e[0],r=e[1];return '<section class="layerCard '+(r.length>1?'sharedLayer':'')+'"><h3><span class=mcdLayer>'+E(l)+'</span> <small>'+l.length+'/10 car. - '+r.length+' bouton(s)</small></h3><div class=layerBtns>'+r.map(function(o){return '<div class=layerBtn><b>'+E(o.code)+'</b><span class=layerMeta>'+E(o.lib)+'<br>SEL '+E(o.sel)+'<br>'+E(o.g+' / '+o.f+' / '+o.t)+'</span><br><button data-open="'+o.code+'">Ouvrir</button></div>'}).join('')+'</div></section>'}).join('');bind();stamp();tools()}
var oldPatch=patch;patch=function(o){var p=oldPatch(o);p.couche_mcd=coucheMCD(o);p.couche_partagee=shared(o);return p}
expJSON=function(){deliver('land2map_validation_v51.json',JSON.stringify({version:'v51',date:new Date().toISOString(),objets:O.map(patch)},null,2))}
expCSV=function(){var rows=[['reseau','groupe_palette','code_bouton','libelle_bouton','selection','couche_mcd','couche_partagee','geometrie','bloc_dwg','icone_palette','icone_bloc','champ','type','liste','visible','force','obligatoire','exportable','valeur_forcee']];O.forEach(function(o){aa(o).forEach(function(a){var f=ff(o);rows.push([o.n,o.g,o.code,o.lib,o.sel,coucheMCD(o),shared(o),o.f=='troncon'?'Ligne':'Point',f.bloc_dwg||'',f.icone_palette||'',f.icone_bloc||'',a.c,a.t,a.li,a.vis,a.fo,a.obl,a.exp,a.val||''])})});deliver('land2map_validation_v51.csv',rows.map(function(r){return r.map(function(x){return '"'+String(x).replaceAll('"','""')+'"'}).join(';')}).join('\n'))}
if(window.json)json.onclick=expJSON;if(window.csv)csv.onclick=expCSV;tools();draw();
})();