(function(){
if(!window.O||!window.C)return;
window.L2M_VIEW=window.L2M_VIEW||'palette';
function E(s){return typeof esc==='function'?esc(s):String(s).replace(/[&<>"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]})}
function av(o,c){var a=(aa(o)||[]).find(function(x){return x.c===c});return a&&(a.val||'')}
function coucheMCD(o){if(!o)return'';if(o.n==='GEN'||/^GEN_/.test(String(o.code||'')))return'ECA_GEN_ANNOTATION';var n=o.n,t=String(o.t||''),c=String(o.code||'');if(/regard_(circulaire|rectangulaire)/.test(t)||/_(REGARD_CIRCULAIRE|REGARD_RECTANGULAIRE)$/.test(c))return'ECA_RSX_'+n+'_REGARD';if(/^chambre($|_tirage$|_technique$|_jonction$)/.test(t)||/_(CHAMBRE|CHAMBRE_TIRAGE|CHAMBRE_TECHNIQUE|CHAMBRE_JONCTION)$/.test(c))return'ECA_RSX_'+n+'_CHAMBRE';if(t==='equipement_specifique'||/_EQUIPEMENT_SPECIFIQUE$/.test(c))return'ECA_RSX_'+n+'_EQUIPEMENT_SPECIFIQUE';return av(o,'calque')||('ECA_RSX_'+n+'_'+String(t||c.replace(n+'_','')).toUpperCase())}
window.coucheMCD=coucheMCD;
function map(a){var m={};(a||O).forEach(function(o){var l=coucheMCD(o);(m[l]=m[l]||[]).push(o)});return m}
function shared(o){return(map()[coucheMCD(o)]||[]).length>1}
function ff(o){try{return typeof ffiles==='function'?ffiles(o):(files(o)||{})}catch(e){return files(o)||{}}}
function okList(o){return(aa(o)||[]).filter(function(a){return a.li&&!C.vals[a.li]}).length===0}
function flt(){var s=q.value.toLowerCase();return O.filter(function(o){var f=ff(o),lay=coucheMCD(o);return o.n==cur&&(!grp.value||o.g==grp.value)&&(!dec.value||deci(o)==dec.value)&&(!s||[o.code,o.lib,o.sel,lay,f.bloc_dwg,f.icone_palette,f.icone_bloc].join(' ').toLowerCase().includes(s))})}
function bind(){$$('[data-open]').forEach(function(b){b.onclick=function(){openPop(b.dataset.open)}});$$('[data-d]').forEach(function(b){b.onclick=function(){setD(b.dataset.c,b.dataset.d)}})}
function addBtn(){var bar=document.querySelector('.bar');if(!bar||document.getElementById('layerViewBtn'))return;var b=document.createElement('button');b.id='layerViewBtn';b.className='layerToggle';b.textContent='Vue couches MCD';b.onclick=function(){window.L2M_VIEW=window.L2M_VIEW==='layers'?'palette':'layers';b.textContent=window.L2M_VIEW==='layers'?'Vue palette':'Vue couches MCD';draw()};bar.appendChild(b)}
var oldStamp=stamp;stamp=function(){oldStamp();var m=map(),ks=Object.keys(m),sh=ks.filter(function(k){return m[k].length>1}).length,reg=ks.filter(function(k){return/_REGARD$/.test(k)}).length,ch=ks.filter(function(k){return/_CHAMBRE$/.test(k)}).length,gen=(m.ECA_GEN_ANNOTATION||[]).length;stats.innerHTML+='<div class=stat><b>Audit couches MCD</b><div class=mcdAudit><div><b>'+ks.length+'</b><span class=muted>Couches</span></div><div><b>'+sh+'</b><span class=muted>Partagées</span></div><div><b>'+reg+'</b><span class=muted>Regards</span></div><div><b>'+ch+'</b><span class=muted>Chambres</span></div><div><b>'+gen+'</b><span class=muted>GEN annotation</span></div></div></div>'}
var oldCard=card;card=function(o){var h=oldCard(o),lay=coucheMCD(o),tag=shared(o)?'Couche partagée':'Couche unique';h=h.replace('<div class=code>'+o.code+'</div>','<div class=code>'+o.code+'</div><div class=mcdline>COUCHE <span class=mcdLayer>'+E(lay)+'</span> <span class="badge info">'+tag+'</span></div>');return h}
var oldOpen=openPop;openPop=function(code){oldOpen(code);var o=O.find(function(x){return x.code==code});if(o)ms.innerHTML=E(o.code+' | '+o.g+' | '+o.sel)+'<br>COUCHE MCD <span class=mcdLayer>'+E(coucheMCD(o))+'</span>'}
var oldDraw=draw;draw=function(){if(window.L2M_VIEW!=='layers'){oldDraw();return}var a=flt(),m=map(a);main.innerHTML='<div class=head><b>'+cur+' - Vue couches MCD</b> <small>'+Object.keys(m).length+' couches / '+a.length+' boutons</small></div>'+Object.entries(m).sort().map(function(e){var l=e[0],r=e[1];return '<section class="layerCard '+(r.length>1?'sharedLayer':'')+'"><h3><span class=mcdLayer>'+E(l)+'</span> <small>'+r.length+' bouton(s)</small></h3><div class=layerBtns>'+r.map(function(o){return '<div class=layerBtn><b>'+E(o.code)+'</b><span class=layerMeta>'+E(o.lib)+'<br>SEL '+E(o.sel)+'<br>'+E(o.g+' / '+o.f+' / '+o.t)+'</span><br><button data-open="'+o.code+'">Ouvrir</button></div>'}).join('')+'</div></section>'}).join('');bind();stamp()}
var oldPatch=patch;patch=function(o){var p=oldPatch(o);p.couche_mcd=coucheMCD(o);p.couche_partagee=shared(o);return p}
expJSON=function(){deliver('land2map_validation_v48.json',JSON.stringify({version:'v48',date:new Date().toISOString(),objets:O.map(patch)},null,2))}
expCSV=function(){var rows=[['reseau','groupe_palette','code_bouton','libelle_bouton','selection','couche_mcd','couche_partagee','geometrie','bloc_dwg','icone_palette','icone_bloc','champ','type','liste','visible','force','obligatoire','exportable','valeur_forcee']];O.forEach(function(o){aa(o).forEach(function(a){var f=ff(o);rows.push([o.n,o.g,o.code,o.lib,o.sel,coucheMCD(o),shared(o),o.f=='troncon'?'Ligne':'Point',f.bloc_dwg||'',f.icone_palette||'',f.icone_bloc||'',a.c,a.t,a.li,a.vis,a.fo,a.obl,a.exp,a.val||''])})});deliver('land2map_validation_v48.csv',rows.map(function(r){return r.map(function(x){return '"'+String(x).replaceAll('"','""')+'"'}).join(';')}).join('\n'))}
if(window.json)json.onclick=expJSON;if(window.csv)csv.onclick=expCSV;addBtn();draw();
})();